#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
source /home/vagrant/.bash_aliases
source /home/vagrant/.bash_autocomplete
source /home/vagrant/.bash_exports
source /home/vagrant/.bash_functions
source /home/vagrant/.bash_options
source /home/vagrant/.bash_prompt

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear system messages (e.g.: system copyright notice, the
# date and time of the last login, the message of the day, etc.)

clear
