#!/bin/bash


# ----------------------------------------------------------------------

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cd..='cd ..'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q='exit'
alias c='clear'
alias ch='history -c && > ~/.bash_history'
alias e='vim'
alias g='git'
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias ll='ls -l'
alias m='man'
alias map='xargs -n1'
alias n='npm'
alias q='exit'
alias rm='rm -rf'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Advanced Packaging Tool

alias apti='sudo apt-get install'
alias aptr='sudo apt-get remove'
alias apts='sudo apt-cache search'
alias aptu='sudo apt-get update \
             && sudo apt-get upgrade'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Empty Trash

alias empty-trash='rm -rf ~/.local/share/Trash/files/*'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Hide/Show desktop icons

alias hide-desktop-icons='gsettings set org.gnome.desktop.background show-desktop-icons false'
alias show-desktop-icons='gsettings set org.gnome.desktop.background show-desktop-icons true'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Get local IP

alias local-ip="ifconfig | \
                | grep 'inet addr' \
                | grep -v '127.0.0.1' \
                | cut -d: -f2 \
                | cut -d' ' -f1"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Lock screen

alias akf='gnome-screensaver-command --lock'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Open

alias o='xdg-open'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Update

alias u='sudo apt-get update \
            && sudo apt-get upgrade \
            && npm install -g npm \
            && npm upgrade -g'



#bash_autocomplete

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    source /etc/bash_completion
fi


# bash Colors

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set LS_COLORS (GNU)
#
#  - `ls` displays colors if the `--color` option is passed
#
#  - the actual colors are configured through the `LS_COLORS`
#    environment variable (built-in defaults are used if this
#    variable is not set)

LS_COLORS=''

LS_COLORS+='no=0;39:'   # global default
LS_COLORS+='di=0;36:'   # directory
LS_COLORS+='ex=0;32:'   # executable file
LS_COLORS+='fi=0;39:'   # file
LS_COLORS+='ec=:'       # non-filename text
LS_COLORS+='mi=1;31:'   # non-existent file pointed to by a symlink
LS_COLORS+='ln=target:' # symbolic link
LS_COLORS+='or=31;01'   # symbolic link pointing to a non-existent file

export LS_COLORS

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Enable color support

if [ -x /usr/bin/dircolors ]; then

    test -r ~/.dircolors \
        && eval "$(dircolors -b ~/.dircolors)" \
        || eval "$(dircolors -b)"

    alias dir='dir --color=auto'
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias grep='grep --color=auto'
    alias ls='ls --color=auto'
    alias vdir='vdir --color=auto'

fi

# bash_exports
# Shell Variables
# http://linux.die.net/man/1/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make vim the default editor
export EDITOR='vim'

# Ignore commands that start with spaces and duplicates
export HISTCONTROL=ignoreboth

# Increase the maximum number of lines of history
# persisted in the Bash history file (default value is 500)
export HISTFILESIZE=10000

# Don't add certain commands to the history file
export HISTIGNORE='&:[bf]g:c:clear:history:exit:q:pwd:* --help'

# Increase the maximum number of commands recorded in the
# command history (default value is 500)
export HISTSIZE=10000

# Prefer US English and use UTF-8 encoding
export LANG='en_US'
export LC_ALL='en_US.UTF-8'

# Use custom `less` colors for man pages
# https://www.gnu.org/software/termutils/manual/termutils-2.0/html_chapter/tput_1.html
export LESS_TERMCAP_md=$'\E[1;32m'   # begin bold mode
export LESS_TERMCAP_me=$'\E[0m'      # end bold mode
#export LESS_TERMCAP_us=$'\E[4;32m'   # begin underscore mode
#export LESS_TERMCAP_ue=$'\E[0m'      # end underscore mode

# Don't clear the screen after quitting a man page
export MANPAGER='less -X'

# Increase the maximum number of lines of history persisted
# in the `Node` REPL history file (default value is 1000)
# https://github.com/nodejs/node/blob/a85f4b5ce5791caf8caa9b31970313c6183a5499/doc/api/repl.markdown#persistent-history
export NODE_REPL_HISTORY_SIZE=10000

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Make Python use UTF-8 encoding for output to stdin/stdout/stderr
export PYTHONIOENCODING='UTF-8'






mkd() {
    [ -n "$*" ] && mkdir -p "$@" && cd "$@"
    #                     └─ make parent directories if needed
}



# bash_logout: Clear console on exit

[ "$SHLVL" == 1 ] \
    && command -v 'clear' &> /dev/null  \
    && clear


# Shell Options

# Shell Options
# http://ss64.com/bash/shopt.html

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Autocorrect typos in path names when using the `cd` command
shopt -s cdspell

# Check the window size after each command and, if necessary, update
# the values of `LINES` and `COLUMNS`
shopt -s checkwinsize

# Save all lines of a multiple-line command in the same history entry
shopt -s cmdhist

# Include filenames beginning with a "." in the filename expansion
shopt -s dotglob

# Use extended pattern matching features
shopt -s extglob

# Append to the history file, rather then overwriting it
shopt -s histappend

# Do not attempt to search the PATH for possible completions when
# completion is attempted on an empty line
shopt -s no_empty_cmd_completion

# Match filenames in a case-insensitive# fashion when performing
# filename expansion
shopt -s nocaseglob

